"""Property-based tests for app.db.status (transition / log_event).

Property 5: Status history is append-only.
  For any sequence of ``transition()`` and ``log_event()`` calls,
  ``status_detail.events`` SHALL be in time order, earlier events SHALL be
  unchanged, and the last status event SHALL equal the ``status`` column.
  Validates: Requirement 4.4

The sequence is generated by Hypothesis as a list of operations (each either a
``transition`` to some status, or a progress ``log_event``) and replayed
against an in-memory ``FakeSession`` / ``FakeDataset`` that mimics the exact two
statements :func:`app.db.status._append_event` runs (``SELECT ... FOR UPDATE``
then the ``jsonb_set(... || :event)`` append) plus the status-column write. No
real database is used, matching ``tests/unit/db/test_status.py``; the ordered,
append-only behaviour against *real* PostgreSQL is covered by the integration
test. ``publish_event`` is patched out so no AWS is touched.
"""

from __future__ import annotations

import copy
from collections.abc import Iterator
from contextlib import contextmanager
from datetime import datetime
from typing import Any
from unittest.mock import patch

from app.db import status as status_mod
from app.db.models import DatasetStatus
from hypothesis import given, settings
from hypothesis import strategies as st

_DATASET_ID = "11111111-1111-1111-1111-111111111111"


# ---------------------------------------------------------------------------
# In-memory fake for the dataset row + session (mirroring tests/unit/db)
# ---------------------------------------------------------------------------


class FakeDataset:
    """Just the fields app.db.status reads/writes on a Dataset row."""

    def __init__(self) -> None:
        self.id = _DATASET_ID
        self.status = DatasetStatus.REQUESTED
        self.status_detail: dict[str, Any] = {"events": []}
        self.updated_at = datetime(2020, 1, 1)
        self.data_version = 2
        self.active_version = 1
        self.metrics: dict[str, Any] | None = {"review_count": 7}


class FakeSession:
    """A minimal Session that services the exact calls app.db.status makes.

    ``_append_event`` runs a ``SELECT ... FOR UPDATE`` (returns a row when the
    dataset exists) then an ``UPDATE ... jsonb_set(... || :event)`` append. This
    fake interprets both against ``dataset.status_detail`` so append and
    ordering can be asserted without PostgreSQL.
    """

    def __init__(self, dataset: FakeDataset) -> None:
        self._dataset = dataset

    def execute(self, statement: Any, params: dict[str, Any] | None = None) -> Any:
        sql = str(statement)
        if "FOR UPDATE" in sql:
            return _FakeResult((1,))
        if "jsonb_set" in sql:
            events = self._dataset.status_detail.setdefault("events", [])
            events.extend((params or {})["event"])
            return _FakeResult(None)
        raise AssertionError(f"unexpected statement: {sql}")

    def get(self, _model: Any, _pk: str) -> FakeDataset:
        return self._dataset


class _FakeResult:
    def __init__(self, first: Any) -> None:
        self._first = first

    def first(self) -> Any:
        return self._first


@contextmanager
def _fake_scope(dataset: FakeDataset) -> Iterator[FakeSession]:
    yield FakeSession(dataset)


# ---------------------------------------------------------------------------
# Strategies: a sequence of transition / log_event operations
# ---------------------------------------------------------------------------

_STATUSES = list(DatasetStatus)

# Each operation is a ("transition", DatasetStatus) or ("log", None).
_operation = st.one_of(
    st.tuples(st.just("transition"), st.sampled_from(_STATUSES)),
    st.tuples(st.just("log"), st.none()),
)

_operations = st.lists(_operation, min_size=1, max_size=20)


# ---------------------------------------------------------------------------
# Property 5
# ---------------------------------------------------------------------------


@settings(max_examples=200)
@given(operations=_operations)
def test_status_history_is_append_only(
    operations: list[tuple[str, DatasetStatus | None]],
) -> None:
    """Property 5: Status history is append-only.

    For any sequence of transition()/log_event() calls, status_detail.events
    SHALL be in time order, earlier events SHALL be unchanged, and the last
    status event SHALL equal the status column.
    Validates: Requirement 4.4
    """
    ds = FakeDataset()

    with (
        patch.object(status_mod, "session_scope", lambda: _fake_scope(ds)),
        patch.object(status_mod, "publish_event"),
    ):
        last_status: DatasetStatus | None = None
        for index, (kind, value) in enumerate(operations):
            # Snapshot the existing events before each call to prove that the
            # call only appends and never rewrites earlier entries.
            before = copy.deepcopy(ds.status_detail["events"])

            if kind == "transition":
                assert value is not None
                status_mod.transition(_DATASET_ID, value, f"op-{index}")
                last_status = value
            else:
                status_mod.log_event(_DATASET_ID, f"op-{index}")

            after = ds.status_detail["events"]

            # Append-only: exactly one new event, and every earlier event is
            # byte-for-byte unchanged.
            assert len(after) == len(before) + 1
            assert after[: len(before)] == before

    events = ds.status_detail["events"]

    # One event per operation, in the order the operations were applied.
    assert len(events) == len(operations)
    assert [e["message"] for e in events] == [f"op-{i}" for i in range(len(operations))]

    # Time order: timestamps are non-decreasing.
    times = [datetime.fromisoformat(str(e["at"])) for e in events]
    assert times == sorted(times)

    # The last *status* event equals the status column (status events carry a
    # non-None status; progress log events carry None).
    status_events = [e for e in events if e["status"] is not None]
    if last_status is not None:
        assert ds.status is last_status
        assert status_events[-1]["status"] == last_status.value
    else:
        # No transition happened: status column stays at its initial value and
        # there are no status events to match.
        assert ds.status is DatasetStatus.REQUESTED
        assert status_events == []
